### ISSUE TITLE
sveltekit warning (or error) message

### ISSUE THREAD

**Issue by demetrius-mp** [ciscoheat/sveltekit-superforms#15]
not sure how to reproduce it, but i got the following warning:

Error: Cannot subscribe to 'page' store on the server outside of a Svelte component, as it is bound to the current request via component context. This prevents state from leaking between users.For more information, see https://kit.svelte.dev/docs/state-management#avoid-shared-state-on-the-server

this is the trace: (highlighted the line where superforms appear)
at get_store (/node_modules/@sveltejs/kit/src/runtime/app/stores.js:68:9)
    at Object.subscribe (/node_modules/@sveltejs/kit/src/runtime/app/stores.js:26:24)
    at subscribe (/node_modules/svelte/internal/index.mjs:57:25)
    at Module.get_store_value (/node_modules/svelte/internal/index.mjs:62:5)
    `at Module.superForm (/node_modules/sveltekit-superforms/dist/client/index.js:59:23)`
    at +page.svelte:13:60
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at Object.default (root.svelte:48:44)
    at eval (/node_modules/@sveltejs/kit/src/runtime/components/layout.svelte:8:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)

**Comment by ciscoheat** [comment]
That's strange, the only subscription to `page` is done within an `if(browser)` check. Does it appear in the latest version as well? (0.5.20)

If it does, can you look in the browser debugger for the line where it happens in the superforms file, and paste it here?

**Comment by demetrius-mp** [comment]
never happened again, guess it was some startup error on svelte kit, im going to close the issue
