### ISSUE TITLE
Superform does not report error found by Zod

### ISSUE THREAD

**Issue by bbtgnn** [ciscoheat/sveltekit-superforms#200]
**Description**

I'm validating an array of files using zod and superforms.
As you can see in the [test repo](https://github.com/bbtgnn/superforms-files-missing-error-demo), the difference between the errors found by zod and superforms is huge.

Superforms should report the correct zod error.

```
------- Superforms error -------
{0: {…}, 1: {…}}
    0: arrayBuffer: undefined
        lastModified: undefined
        name: undefined
        size: undefined
        slice: ƒ slice()stream: undefined
        text: undefined
        type: undefined
        webkitRelativePath: undefined
        [[Prototype]]: Object
    1:
        arrayBuffer:
        undefined
        lastModified: undefined
        name: undefined
        size: undefined
        slice: undefined
        stream: undefined
        text: undefined
        type: undefined
        webkitRelativePath: undefined
        [[Prototype]]: Object
    [[Prototype]]: Object


------- Zod error -------
ZodError: [
  {
    "code": "custom",
    "message": "FILE_TYPE_NOT_ALLOWED",
    "path": [
      0
    ]
  }
]
    at get error [as error] (index.mjs:537:31)
    at ZodArray.parse (index.mjs:636:22)
    at $$self.$$.update (+page.svelte:45:16)
    at update (index.mjs:1343:12)
    at flush (index.mjs:1307:17)
```

**Comment by ciscoheat** [comment]
Schemas with files are not supported by Superforms, see this FAQ: https://superforms.rocks/faq#how-to-handle-file-uploads.
