### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'defaults') at Module.superValidate

### ISSUE THREAD

**Issue by chanmathew** [ciscoheat/sveltekit-superforms#361]
**Description**
Superforms 2.5.0 seems to break when loading a page with superforms.:

```
TypeError: Cannot read properties of undefined (reading 'defaults')
    at Module.superValidate (/home/projects/sveltejs-kit-template-default-hmdz2g/node_modules/sveltekit-superforms/dist/superValidate.js:27:53)
    at load (/home/projects/sveltejs-kit-template-default-hmdz2g/src/routes/+page.server.ts:17:33)
    at Module.load_server_data (/home/projects/sveltejs-kit-template-default-hmdz2g/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:50:42)
    at eval (/home/projects/sveltejs-kit-template-default-hmdz2g/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:41)
```

Here's a repo to reproduce on a clean install: https://stackblitz.com/edit/sveltejs-kit-template-default-hmdz2g?file=src%2Froutes%2F%2Bpage.svelte

**Comment by chanmathew** [comment]
Nvm, as pointed out by Sillvva on discord, need to import the zod adapter function and use it to wrap the schema in the superValidate function:

```
import { zod } from 'sveltekit-superforms/adapters';
// load function
superValidate(zod(registerUserSchema))
// action
superValidate(event, zod(registerUserSchema));
```

As per the migration guide here: https://superforms.rocks/migration-v2#supervalidate
