### ISSUE TITLE
discriminated union with dataType json causing SchemaError

### ISSUE THREAD

**Issue by konstantinblaesi** [ciscoheat/sveltekit-superforms#519]
Error trace

```
SchemaError: [addresses.additional.name] No default value specified for field (can be undefined, but must be explicit)
    at Defaults_traverseAndReplace (/projects/sveltekit-superforms/src/lib/errors.ts:290:11)
    at Errors_traverseAndReplace (/projects/sveltekit-superforms/src/lib/errors.ts:237:4)
    at Data_traverse (/projects/sveltekit-superforms/src/lib/errors.ts:221:3)
    at Module.replaceInvalidDefaults (/projects/sveltekit-superforms/src/lib/errors.ts:303:10)
    at Module.superValidate (/projects/sveltekit-superforms/src/lib/superValidate.ts:139:5)
    at /projects/sveltekit-superforms/src/tests/demo.test.ts:55:13
    at runTest (file:///projects/sveltekit-superforms/node_modules/.pnpm/@vitest+runner@1.6.0/node_modules/@vitest/runner/dist/index.js:781:11)
    at runSuite (file:///projects/sveltekit-superforms/node_modules/.pnpm/@vitest+runner@1.6.0/node_modules/@vitest/runner/dist/index.js:909:15)
    at runSuite (file:///projects/sveltekit-superforms/node_modules/.pnpm/@vitest+runner@1.6.0/node_modules/@vitest/runner/dist/index.js:909:15)
    at runFiles (file:///projects/sveltekit-superforms/node_modules/.pnpm/@vitest+runner@1.6.0/node_modules/@vitest/runner/dist/index.js:958:5) {
  path: 'addresses.additional.name'
}

```
From the repro: The testcase **bad** produces this error trace, testcase **good** works
Basically the feature is to provide one of three possible address types, something like
> addresses.additional.type = { 'type1', 'type2', 'none' }

where the 'none' type has no additional fields

[Repro](https://github.com/konstantinblaesi/sveltekit-superforms/blob/repro/src/tests/demo.test.ts)

<details>
<summary>Code</summary>

```ts
import { zod } from "$lib/adapters/zod.js";
import { superValidate } from "$lib/superValidate.js";
import { stringify } from "devalue";
import { describe, test } from 'vitest';
import { z } from "zod";

const ZodSchema = z.object({
    addresses: z.object({
        additional: z.discriminatedUnion('type', [
            z.object({
                type: z.literal('poBox'),
                name: z.string()
                    // these constraints cause the test failure
                    // Validation error instead of schema error would be expected?
                    .min(1, "min len").max(10, "max len")
                    .default("")
            }),
            z.object({
                type: z.literal('none'),
            }),
        ])
    })
})
const FormSchema = zod(ZodSchema)
type FormSchema = typeof FormSchema['defaults']

async function validate(data: unknown) {
    const formInput = new FormData()

    formInput.set('__superform_json', stringify(data));
    try {
        await superValidate(formInput, FormSchema)
    } catch (err) {
        console.error(err)
        //
        throw err
    }
}

describe("Demo", () => {
    test("Bad", async () => {
        const data = {
            addresses: {
                additional: {
                    type: 'poBox',
                    name: ''
                }
            }
        } satisfies FormSchema;
        await validate(data)
    })

    test("Good", async () => {
        const data = {
            addresses: {
                additional: {
                    type: 'none'
                }
            }
        } satisfies FormSchema;
        await validate(data)
    })
})
```
</details>

Should this kind of schema work ? Should this be modeled differently?

**Comment by ciscoheat** [comment]
You can't stringify `__superform_json` directly, you need to use [devalue](https://www.npmjs.com/package/devalue). Try that and see if it works. Otherwise you should try to add a default value to the schema, as suggested by the error.

**Comment by konstantinblaesi** [comment]
I updated the code. The field addresses.additional.name is a required field and I would expect a validation error when empty string is submitted, but instead I get a schema error / crash from superforms ?

**Comment by konstantinblaesi** [comment]
This schema
```ts
const ZodSchema = z.object({
    addresses: z.object({
        additional: z.discriminatedUnion('type', [
            z.object({
                type: z.literal('poBox'),
                name: z.string()
                    // these constraints cause the test failure
                    // Validation error instead of schema error would be expected?
                    .min(1, "min len").max(10, "max len")
                // .default("")
            }),
            z.object({
                type: z.literal('none'),
            }),
        ])
            .default({ type: 'none', name: '123' })
    })
})
```

fixes the error and produces this result from superValidate

```
RESULT {
  id: '1s92os',
  valid: false,
  posted: true,
  errors: {
    addresses: { additional: { name: [ 'min len' ] } }
  },
  data: { addresses: { additional: { type: 'poBox', name: '' } } }
}
```

but if this is the fix , it is not intuitive since it screems at me in my IDE :D 
![image](https://github.com/user-attachments/assets/05917850-653b-4399-b404-6f8617e23bb6)

**Comment by ciscoheat** [comment]
There was a problem with the recursive check for discriminated unions, will be fixed in the next release. No default will be required.

**Comment by konstantinblaesi** [comment]
Thanks for the fix! Sadly when [assigning a default value on a nested discriminated union](https://github.com/konstantinblaesi/sveltekit-superforms/commit/6b06fe3c8a517c171b2a0617f1aaf0ac7d5ef565) things break. Is this expected or should this work?
